            //Declaration of targets for createObject function for home page

const listTarget = "articles-list__content";
const linkTarget = "articles-list__content--link";
const productTarget = "articles-list__content__product";
const imgProductTarget = "articles-list__content__product__picture";
const featProductTarget = "articles-list__content__product__feature";

/*
            Main function => promise of sendRequest function
            return: array of objects (cameras products) from Orinoco database when resolved or error when rejected
*/

sendRequest("GET", "http://localhost:3000/api/cameras/", null)
.then(responseRequest => {
    nbProductCart(orderStorage);
    addBlocsViews(responseRequest);
})
.catch(error => {
    errorView("\""+error+"\"");
});

/*
            Function to generate products list according products in the database from Orinoco
            Parameters: data => array of objects (products) generated by sendRequest function (parsed)
*/

function addBlocsViews(data) {                                          
    for (let i = 0; i < data.length; i++) 
    {
        let blockRacine = [listTarget,"a",linkTarget];
        let addBlocs = [
            [linkTarget,"section",productTarget,null],
            [productTarget,"aside",imgProductTarget,"<img src=\""+data[i].imageUrl+"\" alt=\"product view\">"],
            [productTarget,"article",featProductTarget,"<h3>"+data[i].name+"</h3><p>"+data[i].description+"</p><p>Prix: "+data[i].price/100+"€</p>"]
        ];
        createObject(blockRacine[0],blockRacine[1],blockRacine[2],null,0);
        generateLinkProduct(blockRacine[2],i,data);
        for (let j = 0; j < addBlocs.length; j++) 
        {
            createObject(addBlocs[j][0],addBlocs[j][1],addBlocs[j][2],addBlocs[j][3],i);
        }
    }
} 

/*
            Function to generate produit.html web page link according to product's id
            Parameters: target => DOM element that will have a link
                        level => number for each element that will have a link 
                        data => array of objects (products) generated by sendRequest function (parsed) for recover Ids
*/

function generateLinkProduct(target,level,data) {                                               
    let blockListProduct = document.getElementsByClassName(target);                             
    blockListProduct[level].setAttribute("href","./Pages/produit.html?id="+data[level]._id);
}