            //Declaration of targets for createObject function for product page    

const productTarget = "article__content";
const imgTarget = "article__content__picture";
const featTarget = "article__content__feature";

/*
            Main function => promise of sendRequest function with Id like parameter
            return: product object according to Id parameter
*/

var param = new URL(document.location).searchParams.get("id");
sendRequest("GET", "http://localhost:3000/api/cameras/"+param, null)
.then(responseRequest => {
    nbProductCart(orderStorage);
    addBlocsViews(responseRequest);
    controlProduct(orderStorage,responseRequest);
    clickToAddProduct(orderStorage,responseRequest);
    ClickToHome();
})
.catch(error => {
    errorView("\""+error+"\"");
});

/*
            Function to add product in cart and set it in browser cache
            Parameter: dataMemory => storage interface that will receive the data (products added to the cart) to be stored in the browser's cache
                       data => product object generated by sendRequest function (parsed)
*/

function clickToAddProduct(dataMemory,data) {
    let order = document.getElementById("article__validation__cart");
    order.addEventListener("click", function() {
        let commentOrder = document.getElementsByClassName(featTarget);
        let input = document.getElementById("lentilles").value;
        data.lenses = input;
        commentOrder[0].innerHTML += "<p>Produit ajouté dans le panier!</p>";
        commentOrder = document.getElementById("article__validation__cart").disabled = true;
        dataMemory.setItem(data._id,JSON.stringify(data));
        nbProductCart(dataMemory);
    });
}

/*
            Function to generate product view bloc according product selectionned in home page 
            Parameter: data => product object generated by sendRequest function (parsed)
*/

function addBlocsViews(data) {
    let addBlocs = [
        [productTarget,"aside",imgTarget,"<img src=\""+data.imageUrl+"\" alt=\"product view\">"],
        [productTarget,"article",featTarget,"<h3>"+data.name+"</h3><p>"+data.description+
        "</p><label for=\"lentilles\">Lentille sélectionnée</label><select id=\"lentilles\" required></select><p>Prix: "+data.price/100+"€</p>"]
    ];
    for (let i = 0; i < addBlocs.length; i++) 
    {
        createObject(addBlocs[i][0],addBlocs[i][1],addBlocs[i][2],addBlocs[i][3],0);
    }
    let choice = document.getElementById("lentilles");
    for (let i = 0; i < data.lenses.length; i++)
    {
        choice.innerHTML += "<option>"+data.lenses[i]+"</option>"
    }
} 

/*
            Function to check the presence of product in cart and desable cart button if product present
            Parameter: dataMemory => storage interface that will receive the data (products added to the cart) to be stored in the browser's cache
                       data => product object generated by sendRequest function (parsed)
*/ 

function controlProduct(dataMemory,data) {
    let commentOrder = document.getElementsByClassName(featTarget);
    if (dataMemory.getItem(data._id) != null) {
            commentOrder[0].innerHTML += "<p>Produit déjà dans le panier!</p>";
            commentOrder = document.getElementById("article__validation__cart").disabled = true;
    }
}

/*
            Function to come back to home when click on the button "liste produit"
*/

function ClickToHome() {
    homeButton = document.getElementById("article__validation__come-back");
    homeButton.addEventListener("click", function() {
        document.location.href = "../index.html";
    });
}