/*
            Main function => promise of sendRequest function with order request like parameter
            return: order object from API (contact object + array products Ids + orderId) when resolved  or error when rejected
*/

sendRequest("POST","http://localhost:3000/api/cameras/order",tempoData.getItem("toSend"))
.then(responseRequest => {
    numberOrderView(responseRequest);
    listProductOrder(responseRequest);
    customerInfos(responseRequest);
    tempoData.clear();
})
    .catch(error => {
        errorView("\""+error+"\"");
});


/*
           function that recover order Id to display it on product list order
           parameter: data => object order generated by sendRequest function (parsed)
*/

function numberOrderView(data) {
    let numberOrder = document.getElementsByClassName("order__products-order__reference");
    numberOrder[0].innerText = "Réf. "+data.orderId;
}

/*
            Function to generate products list order according products present in object order generated by sendRequest function 
            Parameter: data => object order generated by sendRequest function (parsed)
*/

function listProductOrder(data) {
    const tab = ["imageUrl","name","lenses","price"];
    var cost = 0;
    for (let i = 0 ; i < data.products.length; i++) {
        createObject(listProductOrderTarget,"tr",listProductOrderProductTarget,null,0);
        const product = data.products[i];
        for (let j = 0 ; j < tab.length; j++) {
            for (let key in product) {
                if (key == tab[j]) {
                    switch (key) {
                    case "imageUrl":
                        createObject(listProductOrderProductTarget,"td",imageProductResumTarget,"<img src=\""+product[key]+"\" alt=\"product view\">",i);
                        break;
                    case "name":
                        createObject(listProductOrderProductTarget,"td",nameProductResumTarget,product[key],i);
                        break;
                    case "lenses":
                        createObject(listProductOrderProductTarget,"td",lensesProductResumTarget,"Possibilités offertes: "+ product[key],i);
                        break;
                    case "price":
                        createObject(listProductOrderProductTarget,"td",priceProductResumTarget,product[key]/100+"€",i);
                        cost += product[key]/100;
                        break;
                    }
                }   
            }           
        }
    }
    createObject(productOrderCostTarget,"tr",labelProductOrderCostTarget,"<td>Coût total de la commande: </td><td>"+cost+" €</td>" ,0);
}

/*
            Function to generate customer informations bloc according contact informations in order object generated by sendRequest function 
            Parameter: data => object order generated by sendRequest function (parsed)
*/

function customerInfos(data) {
    let infosTarget = ["firstName","lastName","address","city","email"];
    for ( let info of infosTarget) {
        for ( let key in data.contact) {
            if ( info == key) {
                createObject(info,"span",null,data.contact[key],0);
            }
        }
    }
}